name: Create Release

on:
  workflow_dispatch:

permissions:
      contents: write    

jobs:
  test_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run tests and lint
        run: |
          npm install 
          npm run test 
  lint_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run tests and lint
        run: |
          npm install  
          npm run lint            

  build_and_push_image:
    runs-on: ubuntu-latest
    needs: [test_check,lint_check]
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          npm install
          npm run build
          npm run build:docker
      - name: Login to Yandex Container Registry
        run: echo "${{ secrets.YC_TOKEN }}" | docker login --username oauth --password-stdin cr.yandex
      - name: Tag and push images
        run: |
          docker tag shri-infra:latest cr.yandex/${{ secrets.CR_ID }}/app:${{ github.run_number }}
          docker tag shri-infra:latest cr.yandex/${{ secrets.CR_ID }}/app:${{ github.run_number }}_latest
          docker push cr.yandex/${{ secrets.CR_ID }}/app:${{ github.run_number }}
          docker push cr.yandex/${{ secrets.CR_ID }}/app:${{ github.run_number }}_latest
    
  create_release_branch:
    runs-on: ubuntu-latest
    needs: build_and_push_image
    steps:
      - uses: actions/checkout@v3
      - name: Create release branch
        run: |
          git checkout -b release/${{ github.run_number }}
          git push origin release/${{ github.run_number }}

  create_release_tag:
    runs-on: ubuntu-latest
    needs: build_and_push_image
    steps:
      - uses: actions/checkout@v3
      - name: Push tag
        run: |
         git config --global user.email "lu7623@gmail.com"
         git config --global user.name "Lu"
         git tag -a v${{ github.run_number }} -m "Release ${{ github.run_number }}"
         git push origin --tags

  create_issue: 
    runs-on: ubuntu-latest
    needs: build_and_push_image
    steps:
      - name: Set current date 
        run: echo "DATE=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Create an issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Release ${{github.run_number}}
          body: 
             Release ${{ github.run_number }} created.

             - *Date* ${{ env.DATE }}

             - *Author* ${{ github.actor }}

             - *Version* ${{ github.run_number }}

             - *Docker image* cr.yandex/${{ secrets.CR_ID }}/app:${{ github.run_number }}_latest


  changelog:
      runs-on: ubuntu-latest  
      needs:   create_release_branch
      steps:     
        - uses: actions/checkout@v4       
        - name: Checkout releases branch
          run: |
            git checkout release/${{ github.run_number }}     

        - name: Download and Install git-cliff
          run: |  
            curl -L "https://github.com/orhun/git-cliff/releases/download/v2.2.1/git-cliff-2.2.1-x86_64-unknown-linux-gnu.tar.gz" -o git-cliff.tar.gz  
            tar -xzf git-cliff.tar.gz  
            mv git-cliff-2.2.1/git-cliff /usr/local/bin/  
          
        - name: Generate Changelog
          run: git-cliff --config cliff.toml --output CHANGELOG.md
               
            
        - name: Commit Changelog
          run: |  
              git config --global user.email "lu7623@gmail.com"
              git config --global user.name "Lu"
              git add CHANGELOG.md
              git commit -m "docs: Update CHANGELOG"
              git push https://github.com/${{ github.repository }}.git