name: Create Release

on:
  workflow_dispatch:

jobs:
  test_and_lint_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run tests and lint
        run: |
          npm install 
          npm run test 
          npm run lint    

  build_and_push_image:
    runs-on: ubuntu-latest
    needs: test_and_lint_check

    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          npm install
          npm run build
          npm run build:docker
      - name: Login to Yandex Container Registry
        run: echo "${{ secrets.YC_TOKEN }}" | docker login --username oauth --password-stdin cr.yandex
      - name: Tag and push images
        run: |
          docker tag shri-infra:latest cr.yandex/${{ secrets.CR_ID }}/app:${{ github.run_number }}
          docker tag shri-infra:latest cr.yandex/${{ secrets.CR_ID }}/app:${{ github.run_number }}_latest
          docker push cr.yandex/${{ secrets.CR_ID }}/app:${{ github.run_number }}
          docker push cr.yandex/${{ secrets.CR_ID }}/app:${{ github.run_number }}_latest
    
  create_release_branch:
    runs-on: ubuntu-latest
    needs: test_and_lint_check
    steps:
      - uses: actions/checkout@v3
      - name: Create release branch
        run: |
          git checkout -b release/${{ github.run_number }}
          git push origin release/${{ github.run_number }}

  create_release_tag:
    runs-on: ubuntu-latest
    needs: create_release_branch
    steps:
      - uses: actions/checkout@v3
      - name: Push tag
        run: |
         git config --global user.email "lu7623@gmail.com"
         git config --global user.name "Lu"
         git tag -a v${{ github.run_number }} -m "Release ${{ github.run_number }}"
         git push origin --tags