name: Create Release

on:
  workflow_dispatch:

jobs:
  test_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run tests and lint
        run: |
          npm install 
          npm run test 
          npm run lint    

  build_and_push:
    runs-on: ubuntu-latest
    needs: test_lint

    steps:
      - uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.14.0'
      - run: npm install
      - run: npm run build
      - name: Build Docker image
        run: docker build . -t shri-infra:latest
      - name: Log in to Yandex Container Registry
        run: echo "${{ secrets.YC_TOKEN }}" | docker login --username oauth --password-stdin cr.yandex
      - name: Tag and Push Docker images to Yandex Container Registry
        run: |
          docker tag shri-infra:latest cr.yandex/crpp10b1aq4tj99fs4qo/app
          docker tag shri-infra:latest cr.yandex/crpp10b1aq4tj99fs4qo/app_latest
          docker push cr.yandex/crpp10b1aq4tj99fs4qo/app
          docker push cr.yandex/crpp10b1aq4tj99fs4qo/app_latest 