name: Create Release

on:
  workflow_dispatch:

jobs:
  test_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run tests and lint
        run: |
          npm install 
          npm run test 
          npm run lint    

  build_and_push:
    runs-on: ubuntu-latest
    needs: test_lint

    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: |
          npm install
          npm run build
          npm run build:docker
      - name: Login to Yandex Container Registry
        run: echo gh secret set SECRET_NAME"${{ secrets.YC_TOKEN }}" | docker login --username oauth --password-stdin cr.yandex
      - name: Tag and push images
        run: |
          docker tag shri-infra:latest cr.yandex/${{ secrets.CR_ID }}/app:${{ github.run_number }}
          docker tag shri-infra:latest cr.yandex/${{ secrets.CR_ID }}/app:${{ github.run_number }}_latest
          docker push cr.yandex/${{ secrets.CR_ID }}/app:${{ github.run_number }}
          docker push cr.yandex/${{ secrets.CR_ID }}/app:${{ github.run_number }}_latest