name: Create Release

on:
  workflow_dispatch:

permissions:
  contents: write
  issues: write    

jobs:

  test_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run tests and lint
        run: |
          npm install 
          npm run test 
  lint_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run tests and lint
        run: |
          npm install  
          npm run lint            
 

  build_and_push_image:
    runs-on: ubuntu-latest
    needs: [test_check,lint_check]

    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          npm install
          npm run build
          npm run build:docker
      - name: Login to Yandex Container Registry
        run: echo "${{ secrets.YC_TOKEN }}" | docker login --username oauth --password-stdin cr.yandex
      - name: Tag and push images
        run: |
          docker tag shri-infra:latest cr.yandex/${{ secrets.CR_ID }}/app:${{ github.run_number }}
          docker tag shri-infra:latest cr.yandex/${{ secrets.CR_ID }}/app:${{ github.run_number }}_latest
          docker push cr.yandex/${{ secrets.CR_ID }}/app:${{ github.run_number }}
          docker push cr.yandex/${{ secrets.CR_ID }}/app:${{ github.run_number }}_latest
    
  create_release_branch:
    runs-on: ubuntu-latest
    needs: build_and_push_image
    steps:
      - uses: actions/checkout@v3
      - name: Create release branch
        run: |
          git checkout -b release/${{ github.run_number }}
          git push origin release/${{ github.run_number }}

  create_release_tag:
    runs-on: ubuntu-latest
    needs: build_and_push_image
    steps:
      - uses: actions/checkout@v3
      - name: Push tag
        run: |
         git config --global user.email "lu7623@gmail.com"
         git config --global user.name "Lu"
         git tag -a v${{ github.run_number }} -m "Release ${{ github.run_number }}"
         git push origin --tags

  create_issue: 
    runs-on: ubuntu-latest
    needs: build_and_push_image
    steps:
      - name: Set current date 
        run: echo "DATE=$(date +'%Y-%m-%d T%H:%M:%S')" >> $GITHUB_ENV
      - name: Create an issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Release ${{github.run_number}}
          body: |
             Release ${{ github.run_number }} created.

              - *Date*: ${{ env.DATE }}

              - *Author* ${{ github.actor }}

              - *Version* ${{ github.run_number }}

              - *Docker image* cr.yandex/${{ secrets.CR_ID }}/app:${{ github.run_number }}_latest
              
  changelog:
    name: Generate changelog
    needs: [create_issue, create_release_tag, create_release_branch]
    runs-on: ubuntu-latest
    steps:
       - name: Checkout
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
           token: ${{ secrets.GH_PAT }} 
            
       - name: Generate a changelog
         uses: orhun/git-cliff-action@v3
         with:
           config: cliff.toml
           args: --verbose
         env:
              OUTPUT: CHANGELOG.md
              GITHUB_REPO: ${{ github.repository }}
            
       - name: Commit
         run: |
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
            set +e
            git add CHANGELOG.md
            git commit -m "docs: Update changelog"
            git push --force https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git main