name: Create Fix Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Enter release version to fix'
        required: true
      issue_number:
        description: "Enter issue number id"
        required: true
         
jobs:
  test_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run tests 
        run: |
          npm install 
          npm run test 
  lint_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run lint
        run: |
          npm install  
          npm run lint            

  build_and_push_image:
    runs-on: ubuntu-latest
    needs: [test_check,lint_check]
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          npm install
          npm run build
          npm run build:docker
      - name: Login to Yandex Container Registry
        run: echo "${{ secrets.YC_TOKEN }}" | docker login --username oauth --password-stdin cr.yandex
      - name: Tag and push images
        run: |
          docker tag shri-infra:latest cr.yandex/${{ secrets.CR_ID }}/app:${{ github.event.inputs.release_version }}_fix${{ github.run_number }}
          docker tag shri-infra:latest cr.yandex/${{ secrets.CR_ID }}/app:${{ github.event.inputs.release_version }}_latest
          docker push cr.yandex/${{ secrets.CR_ID }}/app:${{ github.event.inputs.release_version }}_fix${{ github.run_number }}
          docker push cr.yandex/${{ secrets.CR_ID }}/app:${{ github.event.inputs.release_version }}_latest
    

  create_fix_release_tag:
    runs-on: ubuntu-latest
    needs: build_and_push_image
    steps:
      - uses: actions/checkout@v3
      - name: Push tag
        run: |
         git config --global user.email "lu7623@gmail.com"
         git config --global user.name "Lu"
         git tag -a v${{ github.event.inputs.release_version }}_fix${{ github.run_number }} -m "Create release fix ${{ github.event.inputs.release_version }}_fix${{ github.run_number }}"
         git push origin --tags

  create_fix_issue_comment: 
    runs-on: ubuntu-latest
    needs: build_and_push_image
    steps:
      - name: Set current date 
        run: echo "DATE=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.inputs.issue_number }}
          body: |
             Fix release ${{ github.event.inputs.release_version }}_fix${{ github.run_number }} created.

             - *Date* ${{ env.DATE }}

             - *Fix author* ${{ github.actor }}

             - *Version*  ${{ github.event.inputs.release_version }}_fix${{ github.run_number }}

             - *Docker image* cr.yandex/${{ secrets.CR_ID }}/app:${{ github.event.inputs.release_version }}_fix${{ github.run_number }}
           