name: Release to prod

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Enter release version'
        required: true
         

jobs:

  check_image:
    runs-on: ubuntu-latest
    steps:
      - name: Check an image 
        run: |
          echo "${{ secrets.YC_TOKEN }}" | docker login --username oauth --password-stdin cr.yandex
          if ! docker manifest inspect cr.yandex/crpk6ta1ej2mrcheq6qs/app:${{ github.event.inputs.release_version }}_latest; then
            echo "Image not found!" && exit 1
          
  run_image:
    runs-on: ubuntu-latest
    needs: check_image
    steps:      
    - name: SSH login and deploy to prod
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_SERVER}}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSWORD }}
        script: |
          echo "Logging in to Yandex Container Registry"
            echo "${{ secrets.YC_TOKEN }}" | docker login --username oauth --password-stdin cr.yandex
            echo "Pulling the latest Docker image"
            docker pull cr.yandex/${{ secrets.CR_ID }}/app:${{ github.event.inputs.release_version }}_latest
            echo "Stopping and removing old container"
            docker kill $(docker ps -q)
            docker rm $(docker ps -a -q)
            echo "Running the new Docker image"
            docker run -d -p 3000:3000 cr.yandex/${{ secrets.CR_ID }}/app:${{ github.event.inputs.release_version }}_latest
  
    