name: Release to prod

on:
  workflow_dispatch:
    inputs:
        release_version:
          description: 'Enter release version to fix'
          required: true
        issue_number:
          description: "Enter issue number id"
          required: true         

jobs:
          
  run_release_to_prod:
    runs-on: ubuntu-latest
    steps:      
    - name: SSH login and deploy to prod
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_SERVER}}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSWORD }}
        script: |
            echo "${{ secrets.YC_TOKEN }}" | docker login --username oauth --password-stdin cr.yandex
            docker pull cr.yandex/${{ secrets.CR_ID }}/app:${{ github.event.inputs.release_version }}_latest
            docker kill $(docker ps -q)
            docker rm $(docker ps -a -q)
            docker run -d -p 3000:3000 cr.yandex/${{ secrets.CR_ID }}/app:${{ github.event.inputs.release_version }}_latest
  
    