name: Release to prod

on:
  workflow_dispatch:
    inputs:
        release_version:
          description: 'Enter release version to fix'
          required: true
        issue_number:
          description: "Enter issue number id"
          required: true         

jobs:
  
  check_release: 
    runs-on: ubuntu-latest
    steps: 
      - name: Login to Yandex Container Registry
        run: echo "${{ secrets.YC_TOKEN }}" | docker login --username oauth --password-stdin cr.yandex
      - name: Check if image exists
        run: |   
          IMAGE=$(docker images | grep cr.yandex/${{ secrets.CR_ID }}/app:${{ github.event.inputs.release_version }}_latest | wc -l)
          test IMAGE = 1
          

  run_release_to_prod:
    runs-on: ubuntu-latest
    needs: check_release
    steps:      
    - name: SSH login and deploy to prod
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_SERVER}}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSWORD }}
        script: |
            echo "${{ secrets.YC_TOKEN }}" | docker login --username oauth --password-stdin cr.yandex
            docker pull cr.yandex/${{ secrets.CR_ID }}/app:${{ github.event.inputs.release_version }}_latest
            docker kill $(docker ps -q)
            docker rm $(docker ps -a -q)
            docker run -d -p 3000:3000 cr.yandex/${{ secrets.CR_ID }}/app:${{ github.event.inputs.release_version }}_latest
  
  create_issue: 
    runs-on: ubuntu-latest
    needs: run_release_to_prod
    steps:
      - name: Set current date 
        run: echo "DATE=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Create an issue
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: Release ${{github.run_number}}
          body: 
             Release ${{ github.event.inputs.release_version }} was successfully deployed to production.

             - *Date* ${{ env.DATE }}

             - *Author* ${{ github.actor }}

             - *Production deployment is running on* http://51.250.36.82:3000/hw/store
 