name: Test

on:
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v3
      - name: Create release branch
        run: |
            git checkout -b test/${{ github.run_number }}
            git push origin test/${{ github.run_number }}

      - name: Download and Install git-cliff
        run: |
          curl -L "https://github.com/orhun/git-cliff/releases/download/v2.2.1/git-cliff-2.2.1-x86_64-unknown-linux-gnu.tar.gz" -o git-cliff.tar.gz  
          tar -xzf git-cliff.tar.gz  
          mv git-cliff-2.2.1/git-cliff /usr/local/bin/

      - name: Generate Changelog
        run: git cliff --config detailed --output CHANGELOG.md

      - name: Commit Changelog
        run: |
          git config --global user.email "lu7623@gmail.com"
          git config --global user.name "Lu"
          git add CHANGELOG.md
          git commit -m "docs: Update CHANGELOG"
          git push origin  test/${{ github.run_number }}
