name: Test

on:
  workflow_dispatch:

permissions:
      contents: write    

jobs:
 
    create_issue:
        runs-on: ubuntu-latest
        steps:
                  - name: Set current date 
                    run: echo "DATE=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
                  - name: Create an issue
                    uses: dacbd/create-issue-action@main
                    with:
                      token: ${{ github.token }}
                      title: Release ${{github.run_number}}
                      body: |
                          Release ${{ github.run_number }} created.
            
                          - *Date*: ${{ env.DATE }}

                          - *Author*: ${{ github.actor }}

                          - *Version*: ${{ github.run_number }}

                          - *Docker image*: cr.yandex/${{ secrets.CR_ID }}/app:${{ github.run_number }}_latest